// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inpyqqqswkabmjzmabqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlucHlxcXFzd2thYm1qem1hYnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzQ5MTYsImV4cCI6MjA2Nzk1MDkxNn0.JpsBOm573J87-8wtnXHg4fxw4pRPSkM7oLm_AtFuFWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});